"use client";

import { useState } from "react";

// The learning profile, as a parent sees it.
//
// Everything here was counted from the database when the page loaded — no AI
// call, no generation cap, no waiting. That is the point: a parent can open this
// the morning of an IEP meeting and it is current.

export type ProfileData = {
  childName: string;
  targetGrade: string;
  generatedAt: string;
  subjects: {
    subject: string;
    working: string;
    target: string;
    pct: number;
    atLevel: boolean;
    assessed: boolean;
  }[];
  standards: { mastered: number; attempted: number; codes: string[] };
  goals: { area: string; goal: string; status: string; evidence: string }[];
  goalsFrom: string | null;
  notes: { count: number; weeks: number; specialists: string[] };
  assessments: { name: string; date: string; score: string }[];
  evidence: { lessons: number; completions: number; firstDay: string | null };
};

const STATUS_LABEL: Record<string, string> = {
  met: "Met",
  on_track: "On track",
  stalled: "Needs work",
  not_started: "Not started",
  // The review says "unclear" when the documents didn't show enough to judge —
  // which is itself worth carrying into a meeting.
  unclear: "No evidence",
};

const statusClass = (s: string) =>
  s === "met" ? "met" : s === "on_track" ? "good" : s === "stalled" ? "warn" : "";

export default function LearningProfile({ data }: { data: ProfileData }) {
  const [copied, setCopied] = useState(false);
  const first = data.childName.split(" ")[0] || data.childName;

  // Export as a self-contained page: no styles to fetch, nothing to break when
  // it is emailed on or opened from a memory stick in a school office.
  function exportHtml() {
    const rows = data.subjects
      .map(
        (s) =>
          `<tr><td>${esc(s.subject)}</td><td>${esc(s.working)}</td><td>${esc(s.target)}</td><td>${
            s.assessed ? (s.atLevel ? "At grade level" : "Working below") : "Not yet assessed"
          }</td></tr>`
      )
      .join("");
    const goals = data.goals.length
      ? data.goals
          .map(
            (g) =>
              `<li><b>${esc(STATUS_LABEL[g.status] ?? g.status)}</b> — ${esc(g.goal)}${
                g.evidence ? `<br><span class="ev">${esc(g.evidence)}</span>` : ""
              }</li>`
          )
          .join("")
      : "<li>No IEP review has been generated yet.</li>";

    const html = `<!doctype html><meta charset="utf-8">
<title>Learning profile — ${esc(data.childName)}</title>
<style>
 body{font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;color:#17273a;max-width:720px;margin:40px auto;padding:0 20px}
 h1{font-size:1.5rem;margin:0 0 4px} .sub{color:#566577;margin:0 0 26px}
 h2{font-size:1rem;text-transform:uppercase;letter-spacing:.08em;color:#566577;margin:30px 0 10px}
 table{border-collapse:collapse;width:100%} td,th{text-align:left;padding:8px 10px;border-bottom:1px solid #d7dee7}
 th{font-size:.8rem;text-transform:uppercase;letter-spacing:.06em;color:#566577}
 ul{padding-left:18px} li{margin-bottom:10px} .ev{color:#566577;font-size:.9rem}
 .foot{margin-top:34px;padding-top:16px;border-top:1px solid #d7dee7;color:#566577;font-size:.86rem}
</style>
<h1>Learning profile — ${esc(data.childName)}</h1>
<p class="sub">${esc(data.targetGrade)} · generated ${esc(data.generatedAt)}</p>
<h2>Where ${esc(first)} is working</h2>
<table><tr><th>Subject</th><th>Working at</th><th>Held to</th><th></th></tr>${rows}</table>
<h2>Standards</h2>
<p>${data.standards.mastered} mastered of ${data.standards.attempted} attempted.</p>
<h2>IEP goals</h2><ul>${goals}</ul>
<h2>Evidence behind this</h2>
<p>${data.evidence.lessons} lessons · ${data.evidence.completions} validated completions · ${
      data.notes.count
    } specialist notes across ${data.notes.weeks} weeks${
      data.evidence.firstDay ? ` · records from ${esc(data.evidence.firstDay)}` : ""
    }.</p>
<p class="foot">Generated by NeuroBridge Academy from ${esc(
      data.childName
    )}'s own records. Figures are counted, not estimated.</p>`;

    const url = URL.createObjectURL(new Blob([html], { type: "text/html" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `learning-profile-${first.toLowerCase()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function copySummary() {
    const lines = [
      `Learning profile — ${data.childName} (${data.targetGrade})`,
      `Generated ${data.generatedAt}`,
      "",
      ...data.subjects.map(
        (s) => `${s.subject}: working at ${s.working}, held to ${s.target}`
      ),
      "",
      `Standards: ${data.standards.mastered} mastered of ${data.standards.attempted} attempted`,
      ...data.goals.map((g) => `${STATUS_LABEL[g.status] ?? g.status} — ${g.goal}`),
    ];
    await navigator.clipboard.writeText(lines.join("\n"));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const thin = data.evidence.lessons === 0 && data.evidence.completions === 0;

  return (
    <>
      <div className="lprof">
        <div className="lprof-head">
          <div>
            <p className="lprof-title">Learning profile</p>
            <p className="lprof-sub">
              {data.childName} · {data.targetGrade}
            </p>
          </div>
          <span className="lprof-stamp">Generated {data.generatedAt}</span>
        </div>

        <div className="lprof-body">
          {thin && (
            <p className="muted" style={{ marginTop: 0 }}>
              There isn&apos;t much history yet, so this profile is thin. It fills in as lessons run
              and scores are recorded.
            </p>
          )}

          <p className="lprof-section">Where {first} is working</p>
          {data.subjects.map((s) => (
            <div key={s.subject} className="lprof-subject">
              <span className="lprof-subject-name">{s.subject}</span>
              <span className="lprof-bar">
                <span className="lprof-bar-fill" style={{ width: `${s.pct}%` }}></span>
              </span>
              <span className="lprof-subject-lvl">
                {s.assessed ? (
                  <>
                    {s.working} <em>→</em> {s.target}
                  </>
                ) : (
                  <span className="muted">Not yet assessed</span>
                )}
              </span>
            </div>
          ))}

          <p className="lprof-section">Standards</p>
          <p className="lprof-line">
            <b>{data.standards.mastered}</b> mastered of <b>{data.standards.attempted}</b> attempted
            {data.standards.attempted === 0 && (
              <span className="muted"> — none recorded yet</span>
            )}
          </p>

          <p className="lprof-section">IEP goals</p>
          {data.goals.length ? (
            <ul className="lprof-goals">
              {data.goals.map((g, i) => (
                <li key={i}>
                  <span className={`lprof-pill ${statusClass(g.status)}`}>
                    {STATUS_LABEL[g.status] ?? g.status}
                  </span>
                  <span>
                    {g.goal}
                    {g.evidence && <em className="lprof-ev">{g.evidence}</em>}
                  </span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="lprof-line muted">
              No IEP review yet — generate one in the IEP support tab and its goals appear here.
            </p>
          )}

          <div className="lprof-foot">
            <span>
              <b>{data.evidence.lessons}</b> lessons
            </span>
            <span>
              <b>{data.notes.count}</b> notes across <b>{data.notes.weeks}</b> weeks
            </span>
            {data.assessments.length > 0 && (
              <span>
                <b>{data.assessments.length}</b> tests taken
              </span>
            )}
          </div>
        </div>
      </div>

      <div className="row" style={{ gap: 8, marginTop: 14, flexWrap: "wrap" }}>
        <button className="btn" onClick={exportHtml}>
          Export for a meeting
        </button>
        <button className="btn quiet" onClick={copySummary}>
          {copied ? "Copied ✓" : "Copy as text"}
        </button>
      </div>

      <p className="muted" style={{ fontSize: "0.85rem", marginTop: 12 }}>
        Every figure here is counted from {first}&apos;s own records, not estimated — and it is
        rebuilt each time you open this page.
      </p>
    </>
  );
}

function esc(s: string): string {
  return String(s).replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!
  );
}
